### ISSUE TITLE
Hide "letter" and "number" section indexes

### ISSUE THREAD

**Issue by oligiter** [solewniczak/dokuwiki-plugin-alphalist#3]
Hi,
I want to use this plugin to automaticaly sort a sidebar.
Can I hide the Letter and Number indexes ?
Your second plugin "alphalist2" could do the job : https://github.com/solewniczak/dokuwiki-plugin-alphalist/issues/1#issuecomment-74658187 but does not accept a page as argument.
Is there an option I can use on alphalist to hide them ?
Or is there a way to include a page (or other source) in alphalist2 ?
Best regards.
Olivier

**Comment by solewniczak** [comment]
Ok, I'll check it out and let you know if it is easy to do.

**Comment by solewniczak** [comment]
Try use the alphalist2 together with include plugin. This should do the trick.

**Comment by oligiter** [comment]
After few experiments, I noticed it's working when I put a bullet in front of the include:
`<alphalist>`
`   * {{page>category:page1}}`
`</alphalist>`
Without this bullet, the include is not displayed.
With page1 a bulleted list, this is making: (note the first bullet at the top hierarchy)
  -  - page1_bullet1
      - page1_bullet2

Wich, with a "-" before the include, makes:
  1.  - page1_bullet1
       - page1_bullet2

Conclusion: This is working for me now, I don't really care about the first top tick. (If anytime you figure a way to get rid of this first bullet, let me know).
Thank you for your time and your plugin. Feel free to close this issue as I am satisfied with this.
